### ISSUE TITLE
Add a screenshot in the readme

### ISSUE THREAD

**Issue by Erotemic** [Nodd/lineprofilergui#13]
Adding a screenshot in the readme will give people most of the information they need on if this is something they want or not. If it looks good and continues to be maintained, I'll add a link to it in the `line_profiler` README itself.

**Comment by Nodd** [comment]
Thanks for your kind words!
Screenhots are definitely planned (see #7) but I'll wait a bit so that the interface is more stabilised. Soon(TM)

**Comment by Nodd** [comment]
@Erotemic Screenshots added 😄
