### ISSUE TITLE
Finalise package management

### ISSUE THREAD

**Issue by Nodd** [Nodd/lineprofilergui#8]
- [x] publish on pypi
- [ ] add tests/coverage
- [ ] add translations
- [x] add licence file
- [x] reference similar projects (spyder and pycharm plugins)
- [ ] conda recipe

**Comment by tony** [comment]
Is it as simple as publishing on pypi though? With pyqt5, it's a little different to install depending on the package manager and system release being ran.

As an example, [calibre](https://github.com/kovidgoyal/calibre) isn't simple as a pypi package, in reality is relies on upstream package maintainers to help out connecting qt5 packages:
- See repology: https://repology.org/project/calibre/versions
- Debian: https://packages.debian.org/sid/source/calibre

What could happen is README docs for installing qt dependencies in the mean time, then possibly submitting packages to brew, debian, etc?

**Comment by Nodd** [comment]
Yeah the most important step is to publish on pypi :) I mainly wanted to write a wishlist here.
I don't know a lot about packaging (this is my first package from scratch!) so I keep it for later...

**Comment by Nodd** [comment]
@tony it's now published on PyPI : https://pypi.org/project/line-profiler-gui/

**Comment by Nodd** [comment]
The remaining points were split into separate issues
